#############################################################################
# Makefile for building: Practice_task-App
# Generated by qmake (3.1) (Qt 6.5.2)
# Project:  Practice_task-App.pro
# Template: app
# Command: G:\Programs\Qt\6.5.2\mingw_64\bin\qmake.exe -o Makefile Practice_task-App.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = G:\Programs\Qt\6.5.2\mingw_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = G:\Programs\Qt\6.5.2\mingw_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = G:\Programs\Qt\6.5.2\mingw_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Practice_task-App.pro G:/Programs/Qt/6.5.2/mingw_64/mkspecs/win32-g++/qmake.conf G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/spec_pre.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/device_config.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/sanitize.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/gcc-base.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/g++-base.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/windows-vulkan.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/g++-win32.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/windows-desktop.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/qconfig.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_archive.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_freetype.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_libpng.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_taglib.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_yaml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3danimation.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dcore.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dextras.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dinput.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dlogic.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquick.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3drender.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3drender_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_activeqt.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_activeqt_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_application_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_common_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_crypto_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_dbus_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_intent_client_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_intent_server_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_launcher_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_main_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_manager_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_monitor_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_notification_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_package_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_shared_main_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_window_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axbase_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axcontainer.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axserver.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axserver_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_charts.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_charts_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_coap.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_coap_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_concurrent.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core5compat.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualization.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_dbus.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_declarativeopcua.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designer.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designer_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_grpc.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_grpc_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_gui.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_gui_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_help.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_help_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_httpserver.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_httpserver_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifmedia.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifmedia_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifvehiclefunctions.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttracker.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttracker_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_interfaceframework.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_interfaceframework_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssettings.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_languageserver_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_linguist.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_location.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_location_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_mqtt.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_mqtt_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimedia.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_network.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_network_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_networkauth.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_nfc.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opcua.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opcua_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opengl.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_png_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioning.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_printsupport.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_protobuf.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_protobuf_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltest.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3d.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysics.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_repparser.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_repparser_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensors.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensors_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialbus.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialport.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_shadertools.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sql.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sql_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachine.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svg.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svg_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_testlib.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_texttospeech.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_tools_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uitools.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserver.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserver_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserverquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webchannel.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_websockets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webview.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webview_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webviewquick.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_widgets.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_xml.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_xml_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt_functions.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt_config.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/win32-g++/qmake.conf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/spec_post.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exclusive_builds.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/toolchain.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/default_pre.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/default_pre.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resolve_config.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exclusive_builds_post.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/default_post.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qml_debug.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/entrypoint.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/precompile_header.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/warn_on.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resources_functions.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resources.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/moc.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/opengl.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/uic.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qmake_use.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/file_copies.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/windows.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/testcase_targets.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exceptions.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/yacc.prf \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/lex.prf \
		Practice_task-App.pro \
		G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Widgets.prl \
		G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Gui.prl \
		G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Core.prl \
		G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6EntryPoint.prl \
		.qmake.stash \
		G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile Practice_task-App.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/spec_pre.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/device_config.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/sanitize.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/gcc-base.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/g++-base.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/windows-vulkan.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/g++-win32.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/common/windows-desktop.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/qconfig.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_archive.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_freetype.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_libpng.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_taglib.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_ext_yaml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3danimation.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3danimation_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dcore.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dcore_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dextras.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dextras_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dinput.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dinput_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dlogic.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquick.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickextras.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickinput.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickrender.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3drender.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_3drender_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_activeqt.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_activeqt_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_application_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_common_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_crypto_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_dbus_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_intent_client_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_intent_server_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_launcher_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_main_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_manager_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_monitor_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_notification_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_package_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_plugininterfaces_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_shared_main_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_appman_window_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axbase_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axcontainer.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axserver.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_axserver_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_charts.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_charts_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_coap.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_coap_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_concurrent.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core5compat.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_core_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualization.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualizationqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_dbus.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_declarativeopcua.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designer.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designer_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_grpc.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_grpc_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_gui.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_gui_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_help.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_help_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_httpserver.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_httpserver_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifmedia.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifmedia_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifremoteobjects_helper_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifvehiclefunctions.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_ifvehiclefunctions_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttracker.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttracker_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttrackerqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_interfaceframework.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_interfaceframework_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_jsonrpc_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssettings.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_languageserver_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_linguist.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_location.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_location_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_mqtt.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_mqtt_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimedia.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_network.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_network_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_networkauth.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_networkauth_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_nfc.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opcua.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opcua_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opengl.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_png_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioning.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_printsupport.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_protobuf.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_protobuf_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcompilerplus_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltest.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3d.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3d_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3deffects.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3deffects_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysics.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dutils.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjects.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_repparser.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_repparser_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensors.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensors_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensorsquick.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sensorsquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialbus.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialport.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_shadertools.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_spatialaudio.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_spatialaudio_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sql.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_sql_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachine.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svg.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svg_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_testlib.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_texttospeech.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_tools_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uitools.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserver.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserver_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_vncserverquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webchannel.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_websockets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webview.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webview_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webviewquick.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_webviewquick_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_widgets.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_xml.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_xml_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt_functions.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt_config.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/win32-g++/qmake.conf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/spec_post.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exclusive_builds.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/toolchain.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/default_pre.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/default_pre.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resolve_config.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exclusive_builds_post.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/default_post.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qml_debug.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/entrypoint.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/precompile_header.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/warn_on.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qt.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resources_functions.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/resources.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/moc.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/opengl.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/uic.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/qmake_use.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/file_copies.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/win32/windows.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/testcase_targets.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/exceptions.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/yacc.prf:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/lex.prf:
Practice_task-App.pro:
G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Widgets.prl:
G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Gui.prl:
G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6Core.prl:
G:/Programs/Qt/6.5.2/mingw_64/lib/Qt6EntryPoint.prl:
.qmake.stash:
G:/Programs/Qt/6.5.2/mingw_64/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile Practice_task-App.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
